config/routes.rb
Tada::Application.routes.draw do
  devise_for :users
  resources :items do
    collection { post :sort }
  end
  root to: "items#index"
end

app/models/item.rb
class Item < ActiveRecord::Base
  acts_as_list
  attr_accessible :title, :position
  validates :user_id, presence: true
  validates :title, presence: true
  after_create :move_to_top
  def complete!
    self.done = true
  end
  def completed?
    self.done
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :token_authenticatable
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :check_user_logged_in!
  helper_method :current_user

  protected
  def check_user_logged_in!
    authenticate_user!
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :find_item, except: [:index, :new, :create, :sort]
  # GET /items
  # GET /items.json
  def index
    @items = current_user.items.order(:position)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = current_user.items.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
      format.js
    end
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.build(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
      format.js
    end
  end

  def sort
    params[:item].each_with_index do |id,index|
      Item.update_all({position: index+1},{id: id})
    end
    render nothing: true
  end

  private
  def find_item
    @item = current_user.items.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
#item_form
  = simple_form_for item, html: { class: 'form-inline', remote: true } do |f|
    = f.input :title, label: false, input_html: { class: "input-75"}
    = f.button :submit, t('.save', default: 'Save'), class: 'btn btn-primary', disable_with: "Saving..."
    = link_to_function t('.close', default: 'Close'), '$(this).closest("li#item_form").remove();',class: 'btn btn-danger'

app/views/items/_item.html.haml
= content_tag_for :li, item, class: "well" do
  = item.title
  = link_to t('.delete'), item_path(item),method: :delete, class: "btn btn-danger pull-right",confirm: t('.confirm', default: "Are you sure?"), remote: true
  = link_to t('.edit'), edit_item_path(item), class: "btn btn-warning pull-right", remote: true

app/views/items/create.js.erb
$("li#item_form").fadeOut(2000).remove();
$("ul#items").prepend('<%= j(render "item", item: @item) %>');

app/views/items/destroy.js.erb
$("li#item_<%= @item.id.to_s%>").fadeOut(2000);
$("li#item_<%= @item.id.to_s%>").remove();

app/views/items/edit.html.haml
- model_class = Item
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render "form", item: @item

app/views/items/edit.js.erb
$("li#item_<%= @item.id.to_s%>").html('<%= j(render "form", item: @item) %>')

app/views/items/index.html.haml
- model_class = Item
.page-header
  %h1 SuperCool Todo List On Fire
%ul{id: "items", "data-update-url" => sort_items_url}
  = render @items

= link_to t('.new', default: t("helpers.links.new")), new_item_path, class: 'btn btn-primary', remote: true

app/views/items/new.html.haml
- model_class = Item
.page-header
  %h1=t '.title', default: t('helpers.titles.new', model: model_class.model_name.human, default: "New #{model_class.model_name.human}")
= render "form", item: @item

app/views/items/new.js.erb
$("ul#items").append("<li class='well' id='item_form'><%= j(render "form", item: @item) %></li>");

app/views/items/show.html.haml
- model_class = Item
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @item.title
%p
  %strong= model_class.human_attribute_name(:done) + ':'
  %br
  = @item.done
%p
  %strong= model_class.human_attribute_name(:position) + ':'
  %br
  = @item.position
%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @item.user_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), items_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_item_path(@item), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), item_path(@item), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/items/update.js.erb
$("li#item_<%= @item.id.to_s%>").replaceWith('<%= j(render "item", item: @item) %>')

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Tada"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", media: "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.brand(href="/") Tada Application
          .nav-collapse.collapse
            %ul.nav
              - if current_user
                %li= link_to "#{current_user.email} Profile", edit_user_registration_path
                %li= link_to t('.logout', default: 'Logout'), destroy_user_session_path, method: :delete

    .container-fluid

      .row-fluid
        .span9
          = bootstrap_flash
          = yield

      %footer
        %p &copy; babinho 2013
        %p No cats were hurt making this application
    = javascript_include_tag "application"